export const SWAP_STEP = {
  PROCESSING: 'PROCESSING',
  SUCCESS: 'SUCCESS',
  FAILED: 'FAILED',
};

export const CLAIM_STEP = {
  PROCESSING: 'PROCESSING',
  SUCCESS: 'SUCCESS',
  FAILED: 'FAILED',
  CLAIMABLE: 'CLAIMABLE',
  CLAIMED: 'CLAIMED',
};

export enum TRANSACTION_STATUS {
  PROCESSING = 1,
  CLAIMABLE = 2,
  CLAIMED = 3,
  FAILED = 4,
  CLAIMED_FAILED = 5,
}

export const TRANSACTION_STATUS_TEXT_SENDER = {
  [TRANSACTION_STATUS.PROCESSING]: 'processing',
  [TRANSACTION_STATUS.CLAIMABLE]: 'unclaimed',
  [TRANSACTION_STATUS.CLAIMED]: 'claimed',
  [TRANSACTION_STATUS.FAILED]: 'failed',
  [TRANSACTION_STATUS.CLAIMED_FAILED]: 'failed',
};

export const TRANSACTION_STATUS_TEXT_RECEIVER = {
  [TRANSACTION_STATUS.PROCESSING]: 'processing',
  [TRANSACTION_STATUS.CLAIMABLE]: 'claimable',
  [TRANSACTION_STATUS.CLAIMED]: 'claimed',
  [TRANSACTION_STATUS.FAILED]: 'failed',
  [TRANSACTION_STATUS.CLAIMED_FAILED]: 'failed',
};

export const TRANSACTION_STATUS_OPTIONS_SENDER = [
  {
    value: TRANSACTION_STATUS.PROCESSING,
    name: `swap_status.${TRANSACTION_STATUS_TEXT_SENDER[TRANSACTION_STATUS.PROCESSING]}`,
    key: TRANSACTION_STATUS.PROCESSING,
  },
  {
    value: TRANSACTION_STATUS.CLAIMABLE,
    name: `swap_status.${TRANSACTION_STATUS_TEXT_SENDER[TRANSACTION_STATUS.CLAIMABLE]}`,
    key: TRANSACTION_STATUS.CLAIMABLE,
  },
  {
    value: TRANSACTION_STATUS.FAILED,
    name: `swap_status.${TRANSACTION_STATUS_TEXT_SENDER[TRANSACTION_STATUS.FAILED]}`,
    key: TRANSACTION_STATUS.FAILED,
  },
  {
    value: TRANSACTION_STATUS.CLAIMED,
    name: `swap_status.${TRANSACTION_STATUS_TEXT_SENDER[TRANSACTION_STATUS.CLAIMED]}`,
    key: TRANSACTION_STATUS.CLAIMED,
  },
];

export const TRANSACTION_STATUS_OPTIONS_RECEIVER = [
  {
    value: TRANSACTION_STATUS.PROCESSING,
    name: `swap_status.${TRANSACTION_STATUS_TEXT_RECEIVER[TRANSACTION_STATUS.PROCESSING]}`,
    key: TRANSACTION_STATUS.PROCESSING,
  },
  {
    value: TRANSACTION_STATUS.CLAIMABLE,
    name: `swap_status.${TRANSACTION_STATUS_TEXT_RECEIVER[TRANSACTION_STATUS.CLAIMABLE]}`,
    key: TRANSACTION_STATUS.CLAIMABLE,
  },
  {
    value: TRANSACTION_STATUS.CLAIMED,
    name: `swap_status.${TRANSACTION_STATUS_TEXT_RECEIVER[TRANSACTION_STATUS.CLAIMED]}`,
    key: TRANSACTION_STATUS.CLAIMED,
  },
];

export const DEFAULT_FILTER_IS_SENDING = [
  TRANSACTION_STATUS.CLAIMABLE,
  TRANSACTION_STATUS.CLAIMED,
  TRANSACTION_STATUS.FAILED,
  TRANSACTION_STATUS.PROCESSING,
];

export const DEFAULT_FILTER_IS_RECEIVING = [
  TRANSACTION_STATUS.CLAIMABLE,
  TRANSACTION_STATUS.CLAIMED,
  TRANSACTION_STATUS.PROCESSING,
];

export enum TRANSACTION_TYPE {
  LOCK = 0,
  UNLOCK = 1,
}
