const TIME_CONSTANTS = {
  DEBOUNCE_SEARCH_TIME: 500,

  TIME_FORMAT: {
    DATE: 'DD-MM-YYYY',
    DATE_FORMAT_REQUEST: 'YYYY/MM/DD',
    TIME: 'HH:mm:ss',
    DATE_TIME: 'DD-MM-YYYY HH:mm:ss',
  },
};

export default TIME_CONSTANTS;
